server:
  port: 8081

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/contact_manager_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql

keycloak:
  realm: valyou_relam
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/auth
  resource: contact_manager
  ssl-required: external
  public-client: true
  bearer-only: true
#  config:
#    file: keycloak.json


