server:
  port: 8081
spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/contact_manager_db
  username: postgres
  password: postgres